version: "3"
services:

  redis:
    image: "redis:alpine"
    expose: 
      - "6379"
    networks:
      - poll-tier
      - back-tier

  db:
    image: postgres:9.4
    #build: .
    volumes:
      - .:/docker-entrypoint/initdb.d
   # environment:
#      - POSTGRES_DB=db
 #     - POSTGRES_USERNAME=aaa
  #    - POSTGRES_PASSWORD=aaa
   #   - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    networks:
      - result-tier
      - back-tier

  poll:
    build: ./poll
    ports:
      - "5000:80"
    networks:
      - poll-tier
    depends_on:
      - redis
    
  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
      - result-tier
    depends_on:
      - db
    
  worker:
    build: ./worker
    networks:
      - back-tier
    depends_on:
      - redis
      - db

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: